default world sample-plugin {
    record plugin-config {
        name: string,
        version: string,
    }
    record response {
        content: string,
    }
    import get-config: func() -> plugin-config
    export gen-response: func(user: string) -> response
}